
const STORAGE_PREFIX='rollenkarten-v12-';
const LEGACY=['rollenkarten-v11-','rollenkarten-v10-','rollenkarten-v9-','rollenkarten-v8-','rollenkarten-v7-','rollenkarten-v6-','rollenkarten-v5-','rollenkarten-v4-','rollenkarten-v3-','rollenkarten-v2-','rollenkarten-'];
let names=[],assignments=[],isResetting=false;
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function key(k){return STORAGE_PREFIX+k}function save(k,v){try{localStorage.setItem(key(k),typeof v==='string'?v:JSON.stringify(v))}catch(e){} status('Gespeichert')}
function load(k,f=''){try{let v=localStorage.getItem(key(k)); if(v!==null)return v; for(const p of LEGACY){v=localStorage.getItem(p+k); if(v!==null)return v}}catch(e){} return f}
function json(k,f){try{return JSON.parse(load(k,JSON.stringify(f)))||f}catch(e){return f}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function status(t){const el=$('[data-save-status]'); if(!el)return; el.textContent=t; el.classList.add('visible'); clearTimeout(status.t); status.t=setTimeout(()=>el.classList.remove('visible'),1600)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function setupDistribution(){const form=$('#nameForm'); if(!form)return; names=json('names',[]); assignments=json('assignments',[]); const renderNames=()=>{const ul=$('#nameList'); ul.innerHTML=names.length?'':'<li class="muted-row">Noch keine Namen eingetragen.</li>'; names.forEach((n,i)=>{const li=document.createElement('li');li.innerHTML=`<span>${esc(n)}</span><button type="button">×</button>`;li.querySelector('button').onclick=()=>{names.splice(i,1);assignments=[];save('names',names);save('assignments',assignments);renderNames();renderAssign()};ul.appendChild(li)})}; const renderAssign=()=>{const res=$('#results'), next=$('#nextToCards'); if(!assignments.length){res.innerHTML='<p class="empty-state">Noch keine Verteilung. Trage Namen ein und starte die Zufallsauswahl.</p>';next?.classList.add('hidden');return} next?.classList.remove('hidden');res.innerHTML=assignments.map(x=>`<article class="assignment ${x.className}"><span>${esc(x.role)}</span><strong>${esc(x.name)}</strong></article>`).join('')}; form.onsubmit=e=>{e.preventDefault();const inp=$('#nameInput');const v=inp.value.trim();if(v&&!names.some(n=>n.toLowerCase()===v.toLowerCase())){names.push(v);assignments=[];save('names',names);save('assignments',assignments);renderNames();renderAssign()}inp.value='';inp.focus()}; $('#assignButton')?.addEventListener('click',()=>{if(names.length<2){$('#results').innerHTML='<p class="empty-state">Bitte mindestens zwei Namen eintragen.</p>';return}assignments=shuffle(names).map((name,i)=>i===0?{name,role:'Lehrkraft',className:'teacher'}:i===1?{name,role:'Schüler/in',className:'student'}:{name,role:'Beobachter/in',className:'observer'});save('assignments',assignments);renderAssign()}); $('#clearButton')?.addEventListener('click',()=>{names=[];assignments=[];save('names',names);save('assignments',assignments);renderNames();renderAssign()}); renderNames();renderAssign()}
function setupFields(){$$('[data-save-key]').forEach(el=>{el.value=load(el.dataset.saveKey,''); el.addEventListener('input',()=>save(el.dataset.saveKey,el.value)); el.addEventListener('change',()=>save(el.dataset.saveKey,el.value))}); $$('[data-preview-key]').forEach(el=>{const v=load(el.dataset.previewKey,'').trim(); el.textContent=v||'Noch keine Eingabe gespeichert.'})}
function listGet(k){return json('list-'+k,[])}function listSave(k,items){save('list-'+k,items)}
function setupListEditors(){$$('.list-editor').forEach(ed=>{const k=ed.dataset.listKey,input=$('[data-list-input]',ed),outEl=$('[data-list-output]',ed);let items=listGet(k); const render=()=>{outEl.innerHTML=items.length?'':'<li class="muted-row">Noch keine Einträge.</li>'; items.forEach((txt,i)=>{const li=document.createElement('li');li.innerHTML=`<span>${esc(txt)}</span><button type="button" aria-label="Eintrag löschen">×</button>`;li.querySelector('button').onclick=()=>{items.splice(i,1);listSave(k,items);render()};outEl.appendChild(li)})}; const add=()=>{const v=input.value.trim(); if(!v)return; items.push(v); input.value=''; listSave(k,items); render(); input.focus()}; $('[data-list-add]',ed)?.addEventListener('click',add); input?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();add()}}); render()})}
function setupListPreviews(){$$('[data-list-preview]').forEach(ul=>{const arr=listGet(ul.dataset.listPreview); ul.innerHTML=arr.length?arr.map(x=>`<li>${esc(x)}</li>`).join(''):'<li class="muted-row">Noch keine Einträge gespeichert.</li>'})}
function clearAll(){isResetting=true;try{Object.keys(localStorage).filter(k=>[STORAGE_PREFIX,...LEGACY].some(p=>k.startsWith(p))).forEach(k=>localStorage.removeItem(k))}catch(e){} location.replace('index.html')}
function setupControls(){$$('[data-save-now]').forEach(b=>b.onclick=()=>{saveVisible();status('Alles gespeichert')}); $$('[data-reset]').forEach(b=>b.onclick=()=>{if(confirm('Alle Eingaben, Reflexionen und Zuordnungen löschen?')) clearAll()})}
function saveVisible(){$$('[data-save-key]').forEach(el=>save(el.dataset.saveKey,el.value||'')); try{save('names',names);save('assignments',assignments)}catch(e){}}
function reflectionEntries(){const keys=['reflexion-verlauf','reflexion-foerdernd','reflexion-belastend','reflexion-wirkung','reflexion-verbesserung']; let arr=[]; keys.forEach(k=>listGet(k).forEach((text,i)=>arr.push({id:k+'-'+i,text,source:k}))); return arr}
function setupMapping(){const pool=$('#statementPool'); if(!pool)return; const cats=['sicherheit','naehe-distanz','kommunikation','kontext','kooperation']; let map=json('theorie-map',{}); cats.forEach(c=>{if(!map[c])map[c]=[]}); const assigned=new Set(Object.values(map).flat()); function itemHtml(item){const div=document.createElement('div');div.className='drag-item';div.draggable=true;div.dataset.id=item.id;div.textContent=item.text;div.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',item.id));return div} const all=reflectionEntries(); function render(){pool.innerHTML=''; all.filter(i=>!assigned.has(i.id)).forEach(i=>pool.appendChild(itemHtml(i))); if(!pool.children.length)pool.innerHTML='<p class="muted">Keine freien Reflexionssätze. Ergänze im Reflexionsbogen einzelne Sätze oder entferne Zuordnungen.</p>'; $$('.drop-card').forEach(card=>{const zone=$('.drop-zone',card),c=card.dataset.drop;zone.innerHTML='';(map[c]||[]).forEach(id=>{const it=all.find(x=>x.id===id);if(!it)return;const div=itemHtml(it);div.title='Doppelklick zum Entfernen';div.ondblclick=()=>{map[c]=map[c].filter(x=>x!==id);assigned.delete(id);save('theorie-map',map);render()};zone.appendChild(div)}); if(!zone.children.length)zone.innerHTML='<p class="muted">Hier ablegen.</p>'})} $$('.drop-card').forEach(card=>{card.addEventListener('dragover',e=>{e.preventDefault();card.classList.add('drag-over')});card.addEventListener('dragleave',()=>card.classList.remove('drag-over'));card.addEventListener('drop',e=>{e.preventDefault();card.classList.remove('drag-over');const id=e.dataTransfer.getData('text/plain');if(!id)return;cats.forEach(c=>map[c]=map[c].filter(x=>x!==id));map[card.dataset.drop].push(id);assigned.add(id);save('theorie-map',map);render()})}); $('[data-save-mapping]')?.addEventListener('click',()=>{save('theorie-map',map);status('Zuordnung gespeichert')}); render()}
function setupExport(){const pdf=$('[data-export-pdf]'),doc=$('[data-export-doc]'); if(!pdf&&!doc)return; const build=()=>{const ass=json('assignments',[]); const cats=[['Verlauf','reflexion-verlauf'],['Beziehungsfördernd','reflexion-foerdernd'],['Konfliktverschärfend','reflexion-belastend'],['Wirkung von Sprache und Körper','reflexion-wirkung'],['Verbesserung','reflexion-verbesserung']]; return `<html><head><meta charset="utf-8"><title>Reflexionsbogen</title><style>body{font-family:Arial,sans-serif;padding:30px;line-height:1.5;color:#20272b}h1{font-size:30px}h2{margin-top:24px}table{border-collapse:collapse;width:100%;margin:12px 0}td,th{border:1px solid #ddd;padding:8px;text-align:left}li{margin:6px 0}</style></head><body><h1>Reflexionsbogen</h1><h2>Rollenverteilung</h2><table><tr><th>Rolle</th><th>Name</th></tr>${ass.map(a=>`<tr><td>${esc(a.role)}</td><td>${esc(a.name)}</td></tr>`).join('')}</table>${cats.map(([t,k])=>`<h2>${t}</h2><ul>${listGet(k).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>—</li>'}</ul>`).join('')}</body></html>`}; pdf.onclick=()=>{const w=open('','_blank');w.document.write(build());w.document.close();setTimeout(()=>w.print(),250)}; doc.onclick=()=>{const blob=new Blob([build()],{type:'application/msword'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rollenspiel-reflexionsbogen.doc';a.click();URL.revokeObjectURL(a.href)}}
window.addEventListener('beforeunload',()=>{if(!isResetting)saveVisible()});
document.addEventListener('DOMContentLoaded',()=>{setupControls();setupDistribution();setupFields();setupListEditors();setupListPreviews();setupMapping();setupExport()});
